apiVersion: v1
kind: PersistentVolume
metadata:
  name: firstpv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kumarezz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: kumarezz
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
    - name: apache
      image: kumarezzz/mynewimage:v1
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/mnt"
          name: firstpv
  volumes:
    - name: firstpv
      persistentVolumeClaim:
        claimName: kumarezz
  imagePullSecrets:
    - name: pullsecret
