apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImEzVnRZWEpsZW5wNk9rdHlhWE5vYVhaQU1UUXpNVEl6IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
